const themes = {
  light: {
    primary: '#aaddff',
    secondary: '#022550',
    highlight: '#36368c',

    editor: {
      background: 'none',
      lineNumber: '#cccccc',
      lineNumberHl: 'black',
      lineNumberHlBackground: '#e0f6ff',
      primary: 'black',
      selection: '#b3d4fc',
      comment: 'slategray',
      commentTag: '#A082BD',
      punctuation: '#999',
      annotation: '#999',
      namespace: 'slategray',
      property: '#e90',
      constant: '#905',
      number: '#905',
      selector: '#690',
      operator: '#9a6e3a',
      keyword: '#07a',
      function: '#DD4A68',
      className: '#DD4A68',
      variable: '#e90',
    },
  },
  dark: {
    primary: '#022550',
    secondary: '#aaddff',
    highlight: '#77c8f9',

    editor: {
      background: '#041f29',
      lineNumber: '#81969A',
      lineNumberHl: '#fff',
      lineNumberHlBackground: '#0e303e',
      primary: '#E0E2E4',
      selection: '#E0E2E4',
      comment: '#7D8C93',
      commentTag: '#A082BD',
      punctuation: '#E8E2B7',
      annotation: '#00FFF8',
      namespace: '#7CA8CF',
      property: '#ee9900',
      constant: '#F77669',
      number: '#FFCD22',
      selector: '#E2B671',
      operator: '#E8E2B7',
      keyword: '#1CCBEF',
      function: '#BCBCBC',
      className: '#82CF75',
      variable: '#ee9900',
    },
  },
};

export default themes;
